name: Deploy Spring app in server

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Spring boot for beginners
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Create docker image # todo create dockerfile
        run: |
          mvn clean
          mvn spring-boot:build-image

      - name: Delete docker container
        run: docker rm -f ${{ github.event.repository.name }}
        continue-on-error: true

      - name: Start docker container
        run: docker run --net shopnetwork --ip 172.24.0.12 --name ${{ github.event.repository.name }} -p 8189:8189 -d ${{ github.event.repository.name }}:0.0.1-SNAPSHOT

      - name: clean trash
        run: docker rmi paketobuildpacks/builder-jammy-base
