name: Deploy Spring app in server

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Spring boot for beginners
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print project name
        run: echo ${{ github.event.repository.name }}
        continue-on-error: true

      - name: Print project name 2
        run: echo ${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}
        continue-on-error: true

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Create docker image
        run: |
          mvn clean
          mvn spring-boot:build-image

      - name: Delete docker container
        run: |
          docker stop github-actions-springboot
          docker rm github-actions-springboot
        continue-on-error: true

      - name: Start docker container
        run: docker run --name github-actions-springboot -p 8189:8189 -d github-actions-springboot:0.0.1-SNAPSHOT


#      - name: Build Docker Image
#        uses: actions/build-push-action@v5
#        with:
#          context: .
#          dockerfile: Dockerfile
#          push: false

