name: Build & Deploy Spring app in github

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Spring boot for beginners
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: create network
        run: docker network create --subnet=172.24.0.0/16 shopnetwork

      - name: create DB container
        run: docker run --name postgres_shop_db -d --net shopnetwork --ip 172.24.0.11 -p 5432:5432 -e POSTGRES_PASSWORD=747482hfsjbc[ -e POSTGRES_USER=adminuser -e POSTGRES_DB=shop_db -v /custom/mount:/var/lib/postgresql/data postgres:latest

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 17
      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml

